### ISSUE TITLE
openMVG_Rig_create_list

### ISSUE THREAD

**Issue by sflotron** [FOXEL-Laboratories/Laboratory-of-Photogrammetry#1]
Implementation of the software that create the sfm_data.json file needed as input for openMVG new pipeline.
- [x] Creation of repository
- [x]  Initialization with current version of listomvg
- [x]  Installation of openMVG package on the computer
- [x]  Update CmakeLists.txt  in order to find openMVG package
- [x]  Creation of sfm_data.json without camera subpose
- [x]  Creation of sfm_data.json with camera subpose
- [x]  Validation of subposes using frustums
- [x] Group intrinsics using hash code in IntrinsicBase (do not longer use deprecated CamInfo)

**Comment by pmoulon** [comment]
- [x] Add an option to support old and new image filename convention.
